// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTeO7Td73DNVmDlEZ7ByQ7x8h-9sAzo-c',
    appId: '1:966384919693:android:5468904adcd97ae475aec4',
    messagingSenderId: '966384919693',
    projectId: 'spota-app',
    storageBucket: 'spota-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvA8Cff4h9Ls69rI3BOvwYt9W2Vz_7b5g',
    appId: '1:966384919693:ios:b8eea3d7c45c1a7275aec4',
    messagingSenderId: '966384919693',
    projectId: 'spota-app',
    storageBucket: 'spota-app.appspot.com',
    androidClientId: '966384919693-2ncl4djahj7sf2avob823utsobfj085k.apps.googleusercontent.com',
    iosClientId: '966384919693-38bftq2jacb62vidvklnohjolnjcerc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUps',
  );
}
